In [2]:
! pip install numpy

In [8]:
import numpy as np

Creating an Array


we can create a NumPy ndarray object by using the array() function

In [ ]:
x = np.array([2,3,4,5,6,7.5])
print(x) # [2.  3.  4.  5.  6.  7.5]
print(type(x)) # <class 'numpy.ndarray'>
y = np.array([2,3,4,5,6,7])
print(y) # [2 3 4 5 6 7]
z = np.array((2,3,4,5,6,7))
print(z) # [2 3 4 5 6 7]

[2.  3.  4.  5.  6.  7.5]
<class 'numpy.ndarray'>
[2 3 4 5 6 7]
[2 3 4 5 6 7]


In [ ]:
a = np.arange(4)
print(a) # [0 1 2 3]

[0 1 2 3]


In [ ]:
b = np.arange(-10,-5,1)
print(b) # [-10  -9  -8  -7  -6]
c = np.arange(-10,-5,-1)
print(c) # []
d = np.arange(10,-4,-20)
print(d) # [10]

[-10  -9  -8  -7  -6]
[]
[10]


In [53]:
a1 = np.random.random((10))
print("first",a1)
print()
a2 = np.random.random(size=(10))
print("second",a2)
print()
a3 = np.random.random(size=(4,3))
print("third",a3)
print()
a4 = np.random.random(size=(3,3,3))
print("fourth",a4)

first [0.22535513 0.98997489 0.95093618 0.67867578 0.05664255 0.28615714
 0.18276753 0.99385206 0.63189237 0.06374071]

second [0.78731825 0.8850025  0.45395711 0.26289206 0.05799866 0.15475006
 0.69515808 0.52761697 0.94942707 0.37510534]

third [[0.43638989 0.90568272 0.47700042]
 [0.9011871  0.52278745 0.09320464]
 [0.09606705 0.52366352 0.02554863]
 [0.47482565 0.81587112 0.77066348]]

fourth [[[1.21246151e-01 4.36365901e-01 7.61809540e-01]
  [4.92480893e-04 9.83560682e-01 4.78796847e-02]
  [4.28564661e-01 2.77829306e-01 8.25875305e-01]]

 [[9.84071130e-01 3.31100305e-01 2.52344313e-01]
  [8.45846253e-01 8.24054858e-01 8.93657674e-01]
  [7.89747064e-01 9.12526356e-01 3.47888729e-01]]

 [[7.25219976e-01 8.10222032e-01 2.33533876e-01]
  [2.15499109e-01 3.68683264e-01 1.43839383e-01]
  [3.06535139e-02 9.64102826e-01 7.17608334e-01]]]


In [ ]:
x1 = np.random.randint(50,size=6) # one dimensional
x2 = np.random.randint(10,size=(3,4)) # one dimensional
x3 = np.random.randint(10,size=(3,4,5)) # one dimensional

print(x1)
print()
print(x2)
print()
print(x3)
print()
print(x3.ndim)


[45 42  1 16 10 45]
[[7 7 8 8]
 [3 7 5 6]
 [8 5 4 9]]

[[[5 6 2 9 0]
  [5 8 1 1 3]
  [0 6 2 5 4]
  [8 8 9 6 1]]

 [[1 2 1 1 4]
  [2 2 6 3 3]
  [6 2 3 1 5]
  [8 3 7 6 6]]

 [[8 4 4 7 2]
  [4 3 3 4 4]
  [7 9 7 4 9]
  [8 3 9 3 1]]]


In [62]:
arr = np.array(1)
print(arr)
print('Dimension :',arr.ndim)

1
Dimension : 0


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print('Dimension :',arr.ndim)

[1 2 3 4 5]
Dimension : 1
3


In [65]:
arr2 = np.array([[1,2,3,],[1,2,4]])
print(arr2)
print('Dimension :',arr2.ndim)

[[1 2 3]
 [1 2 4]]
Dimension : 2


In [67]:
arr3 = np.array([[[1,2,3,],[1,2,4]],[[1,2,3,],[1,2,4]]])
print(arr3)
print('Dimension :',arr3.ndim)

[[[1 2 3]
  [1 2 4]]

 [[1 2 3]
  [1 2 4]]]
Dimension : 3


In [68]:
arr4 = np.random.randint(50,size=(3,4,5,2))
print(arr4)
print('Dimension :',arr4.ndim)

[[[[40  5]
   [22 15]
   [35 35]
   [18 11]
   [28  2]]

  [[43 10]
   [20  3]
   [19 27]
   [33 11]
   [35 36]]

  [[29 35]
   [40 45]
   [ 9  3]
   [14 13]
   [ 7 29]]

  [[31 29]
   [29 40]
   [42 48]
   [13 11]
   [33  4]]]


 [[[15 27]
   [28 45]
   [16 37]
   [37 19]
   [23 43]]

  [[35 12]
   [41  4]
   [17 20]
   [24  2]
   [12 12]]

  [[10  6]
   [19  7]
   [46 29]
   [29 13]
   [20 24]]

  [[30 31]
   [27 42]
   [44 15]
   [ 2 15]
   [21 32]]]


 [[[ 7 24]
   [10 47]
   [ 3  1]
   [27 34]
   [ 8  6]]

  [[12 25]
   [20 12]
   [21 40]
   [45 10]
   [16 27]]

  [[36 49]
   [36 21]
   [43 40]
   [33 29]
   [33 48]]

  [[ 3 12]
   [34  6]
   [45 43]
   [24 38]
   [31 39]]]]
Dimension : 4


In [69]:
arr4 = np.random.randint(50,size=(3,4,5))
print(arr4)
print('Dimension :',arr4.ndim)

[[[27 43 38 13 45]
  [26 32 28 38  8]
  [18 34 33  1 14]
  [47  8 15 24  3]]

 [[ 5 41 31 26  7]
  [ 6 17 47 12 15]
  [ 3 38 12 49  6]
  [28  4 10 12 16]]

 [[16 11 48 22 14]
  [49 25  8 10 12]
  [40 43 15 26  9]
  [33  4 14 24 43]]]
Dimension : 3


In [72]:
# indexing in numpy array
# reshape

arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,4,3)

print(arr1)
print()
print(arr2)
print()
print(arr3)



[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [75]:

arr1 = np.arange(10)
print(arr1[0])
print(arr1[2])
print(arr1[-1])
print(arr1[-5])


0
2
9
5


In [90]:
arr2 = np.arange(12).reshape(3,4)
print(arr2)
print(arr2[1,2])
print(arr2[-1,2])
print(arr2[2,-3])
print(arr2[-3,-1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
10
9
3


In [96]:
arr3 = np.arange(24).reshape(2,4,3)
print(arr3)
print(arr3[1,2,2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
20


In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,4,3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(arr1[3:8:1])
print(arr1[::])
print(arr1[::-1])
print(arr1[2::2])

[3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


In [ ]:
print(arr2)
print(arr2[-1::-2,-1::-3])
print(arr2[1::,0::2])
print(arr2[1::,0::-2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11  8]
 [ 3  0]]
[[ 4  6]
 [ 8 10]]


In [24]:
print(arr2)
print()
print(arr2[0,:])
print()
print(arr2[:,0])
print()
print(arr2[1:,1:])
print()
print(arr2[::2,:2:])
print()



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[0 4 8]

[[ 5  6  7]
 [ 9 10 11]]

[[0 1]
 [8 9]]



In [36]:
print(arr3)
print()
print(arr3[1,1::2,::2])
print()
print(arr3[0])
print()
print(arr3[0,0])
print()
print(arr3[1,:3])
print()
print(arr3[0,:2,::2])



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

[[15 17]
 [21 23]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]


In [43]:
print(arr3[::,::3,::2])
print("-----------------------------------------------------------------------------------")
print(arr3[::-1,-2::-2,-1::-2])
print("-----------------------------------------------------------------------------------")
print(arr3[::-1,-2::-1,-2::-1])

[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]
-----------------------------------------------------------------------------------
[[[20 18]
  [14 12]]

 [[ 8  6]
  [ 2  0]]]
-----------------------------------------------------------------------------------
[[[19 18]
  [16 15]
  [13 12]]

 [[ 7  6]
  [ 4  3]
  [ 1  0]]]


In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1.1,2.2,3.3,4.4,5.5])

# Here "dtypes" specifies the type of element contained in the array
print(a1.dtype)
print(a2.dtype)

# Number of bytes occupied by indivisual array element are avalible through "itemsize"
print(a1.itemsize)
print(a2.itemsize)

# Number of bytes occupied by entire element are avalible through "nbytes"
print(a1.nbytes)
print(a2.nbytes)



int64
float64
8
8
40
40


In [50]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(a1.ndim)
print(a2.ndim)

print(a1.shape)
print(a2.shape)

print(a1.size)
print(a2.size)


1
2
(5,)
(2, 5)
5
10


Numpy array function

In [ ]:
# zeros create arrays of 0s
print(np.zeros(10))
print()
print(np.zeros((3,6),dtype='int'))
print()
print(np.zeros((2,3,2))) # there 2 is representing total number of 


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [55]:
# ones create arrays of 1s
print(np.ones(10))
print()
print(np.ones((3,6),dtype='int'))
print()
print(np.ones((2,3,2))) # there 2 is representing total number of 


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [56]:
np.identity(4,dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [57]:
np.identity(3,dtype='int')


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])